## ************* Pivot Tables *************

In [1]:
import numpy as np
import pandas as pd
print("Import Successfully")

Import Successfully

### Pivot Tables

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df=pd.DataFrame(data)

In [3]:
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    462     75   John
1  2023-01-02       B   West    523     24   Mary
2  2023-01-03       C  North    752     48    Bob
3  2023-01-04       D  South    930     44  Alice
4  2023-01-05       A   East    550     43   John
5  2023-01-06       B   West    565     68   Mary
6  2023-01-07       C  North    741     68    Bob
7  2023-01-08       D  South    413     33  Alice
8  2023-01-09       A   East    384     18   John
9  2023-01-10       B   West    642     83   Mary
10 2023-01-11       C  North    448     46    Bob
11 2023-01-12       D  South    278     73  Alice
12 2023-01-13       A   East    998     89   John
13 2023-01-14       B   West    211     91   Mary
14 2023-01-15       C  North    462     36    Bob
15 2023-01-16       D  South    458     13  Alice
16 2023-01-17       A   East    983     24   John
17 2023-01-18       B   West    805     96   Mary
18 2023-01-19       C  North    577     52    Bob
19 2023-01-20       D  South    227     62  Alice

In [4]:
df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    462     75   John  January      Q1
1  2023-01-02       B   West    523     24   Mary  January      Q1
2  2023-01-03       C  North    752     48    Bob  January      Q1
3  2023-01-04       D  South    930     44  Alice  January      Q1
4  2023-01-05       A   East    550     43   John  January      Q1
5  2023-01-06       B   West    565     68   Mary  January      Q1
6  2023-01-07       C  North    741     68    Bob  January      Q1
7  2023-01-08       D  South    413     33  Alice  January      Q1
8  2023-01-09       A   East    384     18   John  January      Q1
9  2023-01-10       B   West    642     83   Mary  January      Q1
10 2023-01-11       C  North    448     46    Bob  January      Q1
11 2023-01-12       D  South    278     73  Alice  January      Q1
12 2023-01-13       A   East    998     89   John  January      Q1
13 2023-01-14       B   West    211     91   Mary  January      Q1
14 2023-01-15       C  North    462     36    Bob  January      Q1
15 2023-01-16       D  South    458     13  Alice  January      Q1
16 2023-01-17       A   East    983     24   John  January      Q1
17 2023-01-18       B   West    805     96   Mary  January      Q1
18 2023-01-19       C  North    577     52    Bob  January      Q1
19 2023-01-20       D  South    227     62  Alice  January      Q1

In [9]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     550.0    NaN    NaN    NaN
North      NaN    NaN  577.0    NaN
South      NaN    NaN    NaN  413.0
West       NaN  565.0    NaN    NaN

In [10]:
pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     675.4    NaN    NaN    NaN  49.8   NaN   NaN   NaN
North      NaN    NaN  596.0    NaN   NaN   NaN  50.0   NaN
South      NaN    NaN    NaN  461.2   NaN   NaN   NaN  45.0
West       NaN  549.2    NaN    NaN   NaN  72.4   NaN   NaN

### Cross Tabs

In [18]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0