### Pandas Practise of DataFrame

In [2]:
import numpy as np
import pandas as pd

### Creating a DataFrame

In [3]:
data={
    "Name":['John','Aman','Naman','Vikas'],
    "Age":[20,21,19,22],
    'City':['Bhopal','Indore','Reva','Nagpur'],
    'Salary':[10000,25000,15000,20000]
}

In [4]:
df=pd.DataFrame(data)
df

    Name  Age    City  Salary
0   John   20  Bhopal   10000
1   Aman   21  Indore   25000
2  Naman   19    Reva   15000
3  Vikas   22  Nagpur   20000

### Create dataframe using List

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [6]:
df2=pd.DataFrame(data_list,)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [7]:
columns=["Name",'Age','City',"Salary"]
df3=pd.DataFrame(data_list,columns=columns)
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selection and Indexing of Columns

In [8]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df3['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [10]:
df3["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [11]:
df3[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### Creating a new Column

In [20]:
df3["Designation"]=["Manager","Director","Leader","HR"]
df3

    Name  Age      City  Salary Designation
0   John   28  New York   65000     Manager
1   Anna   34     Paris   70000    Director
2  Peter   29    Berlin   62000      Leader
3  Linda   42    London   85000          HR

### Removing Columns

In [21]:
df3.drop("Designation",axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
df3

    Name  Age      City  Salary Designation
0   John   28  New York   65000     Manager
1   Anna   34     Paris   70000    Director
2  Peter   29    Berlin   62000      Leader
3  Linda   42    London   85000          HR

In [23]:
df3.drop("Designation",axis=1,inplace=True)

In [24]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
#axis by default is 0
#inplace is by default is false it doest not change the original data
df3.drop(0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [26]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selecting  Rows

In [27]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df3.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [34]:
df3.loc[[1,3]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [35]:
df3.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

### Selecting Subsets of Rows and Columns

In [36]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
df.loc[[0,1]][["City","Salary"]]

     City  Salary
0  Bhopal   10000
1  Indore   25000

In [49]:
#Indexing and Slicing
df3.loc[0:3:2][["Name","City"]]

    Name      City
0   John  New York
2  Peter    Berlin

### Conditional Selection

In [50]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [54]:
#only want to see the people whose age is above 30 
df3[df3['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [60]:
df3[(df3['Age']>30) & (df3['Salary']>75000)]

    Name  Age    City  Salary
3  Linda   42  London   85000